# Generated by Django 6.0.5 on 2026-05-11 10:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='tasks',
        ),
        migrations.AlterField(
            model_name='board',
            name='member',
            field=models.ManyToManyField(blank=True, null=True, related_name='boards', to=settings.AUTH_USER_MODEL),
        ),
    ]
