# Generated by Django 6.0.5 on 2026-05-11 11:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0002_remove_board_tasks_alter_board_member'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='tasks_high_prio_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='board',
            name='tasks_to_do_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='board',
            name='ticket_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='board',
            name='member',
            field=models.ManyToManyField(blank=True, related_name='boards', to=settings.AUTH_USER_MODEL),
        ),
    ]
