# Generated by Django 6.0.5 on 2026-05-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0003_board_tasks_high_prio_count_board_tasks_to_do_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='member_count',
            field=models.IntegerField(default=0),
        ),
    ]
