# Generated by Django 6.0.5 on 2026-05-12 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0005_alter_board_member_alter_board_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='member_count',
        ),
        migrations.RemoveField(
            model_name='board',
            name='tasks_high_prio_count',
        ),
        migrations.RemoveField(
            model_name='board',
            name='tasks_to_do_count',
        ),
        migrations.RemoveField(
            model_name='board',
            name='ticket_count',
        ),
        migrations.AlterField(
            model_name='board',
            name='member',
            field=models.ManyToManyField(related_name='boards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='board',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_boards', to=settings.AUTH_USER_MODEL),
        ),
    ]
