# Generated by Django 6.0.5 on 2026-05-12 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0006_remove_board_member_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='member',
            new_name='members',
        ),
    ]
